### ISSUE TITLE
Minimum screen width ?

### ISSUE THREAD

**Issue by victor-gabou** [creativelive/appear#10]
Hello,

Is there a minimum screen width needed to use appear ?
When my screen width is under 495px, appear and disappear functions aren't launched, is it normal ?

**Comment by victor-gabou** [comment]
It's not always at 495px, here under 230px the library doesn't work : http://codepen.io/victor-gabou/pen/Jbzzdw

**Comment by JustinBeaudry** [comment]
@victor-gabou There is no minimum size requirement. There is most likely an issue with the way you are using the library. Your codepen example isn't up at the moment. Closing this issue. Feel free to comment here if you can post an example of the issue.
