### ISSUE TITLE
appear.js in bower.io

### ISSUE THREAD

**Issue by lucho20pt** [creativelive/appear#12]
Hello guys, 

I love this appear version, the way appear {} is takin place
My issue is just one, i would like to download appear.js from bower.io
I found there to many appears type fr ex jquery.appear, but i am not finding this version

Does it exist there in bower.io ? Can you guys upload it there ?

Many thanks, 
king regards

**Comment by JustinBeaudry** [comment]
At this time Appear is not in the bower registry, and we don't have a plan in-place to put it there.

**Comment by JustinBeaudry** [comment]
Appear is now in the bower registry.
