### ISSUE TITLE
<ie9 support?

### ISSUE THREAD

**Issue by ryanjadhav** [creativelive/appear#4]
Currently we're using `window.addEventListener` in this project. To support older versions of IE (<IE9) we should use a function like: 

```
function addListener (eventType, cb) {
  if (addEventListener) {
    addEventListener(eventType, cb, false); 
  } else if (attachEvent)  {
    attachEvent(eventType, cb);
  }
}

function removeListener (eventType, cb) {
  if (removeEventListener) {
    removeEventListener(eventType, cb, false); 
  } else if (removeEvent)  {
    removeEvent(eventType, cb);
  }
}
```

**Comment by ryanjadhav** [comment]
do we want <ie9 support?

**Comment by diffsky** [comment]
There might also be changes needed in the `track` and `viewable` functions. When making appear I decided to support ie9 and up, but that's not explicitly stated and maybe it should
