### ISSUE TITLE
Not capturing live added elements

### ISSUE THREAD

**Issue by umutkirgoz** [creativelive/appear#7]
As you know, **elements** is captured on init time (documentReady). 

```
 elements: function elements(){
    // work with all elements with the class "track"
    return document.getElementsByClassName('gptAds');
  }
```

captures all elements with class **gptAds**, if I add new elements with that class, they are not tracked by **appear**

**Comment by salvatorious** [comment]
You'll need to call appear again after the new live elements are added. Appear attaches the listeners to elements already in the dom when it's called.

**Comment by JustinBeaudry** [comment]
@salvatorious Is exactly right! We do welcome PR's and/or enhancement tickets!
